-- Compatibilidade entre propostas comerciais e Ordens de Serviço.
alter table public.sales_proposals
  add column if not exists proposal_number bigint generated by default as identity;

create unique index if not exists sales_proposals_proposal_number_idx
  on public.sales_proposals(proposal_number);

-- Mantém compatibilidade com consultas antigas que utilizavam total_value.
alter table public.sales_proposals
  add column if not exists total_value numeric(14,2) generated always as (total_amount) stored;
