-- Estrutura operacional das Ordens de Serviço da MM Energia Solar.

create table if not exists public.service_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  client_id uuid references public.clients(id) on delete set null,
  proposal_id uuid references public.sales_proposals(id) on delete set null,
  appointment_id uuid references public.appointments(id) on delete set null,
  status text not null default 'Aguardando materiais' check (status in (
    'Aguardando materiais',
    'Agendada',
    'Equipe em deslocamento',
    'Instalação iniciada',
    'Testes elétricos',
    'Documentação',
    'Homologação',
    'Concluída',
    'Cancelada'
  )),
  service_type text not null default 'Instalação fotovoltaica',
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  customer_name text not null,
  customer_phone text,
  installation_address text,
  city text,
  state text default 'SP',
  assigned_team text,
  responsible_user_id uuid references auth.users(id) on delete set null,
  notes text,
  technical_notes text,
  customer_observations text,
  total_cost numeric(14,2) not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_order_items (
  id uuid primary key default gen_random_uuid(),
  service_order_id uuid not null references public.service_orders(id) on delete cascade,
  equipment_id uuid references public.equipment(id) on delete set null,
  description text not null,
  category text,
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit text not null default 'un',
  unit_cost numeric(14,2) not null default 0 check (unit_cost >= 0),
  reserved boolean not null default false,
  used_quantity numeric(12,3) not null default 0 check (used_quantity >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_order_checklist (
  id uuid primary key default gen_random_uuid(),
  service_order_id uuid not null references public.service_orders(id) on delete cascade,
  section text not null default 'Instalação',
  item text not null,
  position integer not null default 0,
  required boolean not null default true,
  completed boolean not null default false,
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_order_photos (
  id uuid primary key default gen_random_uuid(),
  service_order_id uuid not null references public.service_orders(id) on delete cascade,
  stage text not null default 'Durante' check (stage in ('Antes', 'Durante', 'Depois', 'Documento', 'Ocorrência')),
  storage_path text not null,
  caption text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.service_order_signatures (
  id uuid primary key default gen_random_uuid(),
  service_order_id uuid not null references public.service_orders(id) on delete cascade,
  signer_name text not null,
  signer_document text,
  signature_data text not null,
  acceptance_text text,
  signed_at timestamptz not null default now(),
  latitude numeric(10,7),
  longitude numeric(10,7),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists service_orders_client_idx on public.service_orders(client_id);
create index if not exists service_orders_proposal_idx on public.service_orders(proposal_id);
create index if not exists service_orders_status_idx on public.service_orders(status);
create index if not exists service_orders_scheduled_idx on public.service_orders(scheduled_at);
create index if not exists service_order_items_order_idx on public.service_order_items(service_order_id);
create index if not exists service_order_checklist_order_idx on public.service_order_checklist(service_order_id, position);
create index if not exists service_order_photos_order_idx on public.service_order_photos(service_order_id, created_at desc);
create index if not exists service_order_signatures_order_idx on public.service_order_signatures(service_order_id, signed_at desc);

alter table public.service_orders enable row level security;
alter table public.service_order_items enable row level security;
alter table public.service_order_checklist enable row level security;
alter table public.service_order_photos enable row level security;
alter table public.service_order_signatures enable row level security;

drop policy if exists "service_orders_authenticated_all" on public.service_orders;
create policy "service_orders_authenticated_all" on public.service_orders for all to authenticated
using (public.is_active_user()) with check (public.is_active_user());

drop policy if exists "service_order_items_authenticated_all" on public.service_order_items;
create policy "service_order_items_authenticated_all" on public.service_order_items for all to authenticated
using (public.is_active_user()) with check (public.is_active_user());

drop policy if exists "service_order_checklist_authenticated_all" on public.service_order_checklist;
create policy "service_order_checklist_authenticated_all" on public.service_order_checklist for all to authenticated
using (public.is_active_user()) with check (public.is_active_user());

drop policy if exists "service_order_photos_authenticated_all" on public.service_order_photos;
create policy "service_order_photos_authenticated_all" on public.service_order_photos for all to authenticated
using (public.is_active_user()) with check (public.is_active_user());

drop policy if exists "service_order_signatures_authenticated_all" on public.service_order_signatures;
create policy "service_order_signatures_authenticated_all" on public.service_order_signatures for all to authenticated
using (public.is_active_user()) with check (public.is_active_user());

drop trigger if exists service_orders_updated_at on public.service_orders;
create trigger service_orders_updated_at before update on public.service_orders
for each row execute procedure public.set_updated_at();

drop trigger if exists service_order_items_updated_at on public.service_order_items;
create trigger service_order_items_updated_at before update on public.service_order_items
for each row execute procedure public.set_updated_at();

drop trigger if exists service_order_checklist_updated_at on public.service_order_checklist;
create trigger service_order_checklist_updated_at before update on public.service_order_checklist
for each row execute procedure public.set_updated_at();

create or replace function public.seed_service_order_checklist()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.service_order_checklist (service_order_id, section, item, position) values
    (new.id, 'Preparação', 'Confirmar endereço e contato do cliente', 10),
    (new.id, 'Preparação', 'Conferir módulos, inversor e estruturas', 20),
    (new.id, 'Preparação', 'Conferir cabos, proteções e conectores', 30),
    (new.id, 'Segurança', 'Conferir EPIs e condições do telhado', 40),
    (new.id, 'Instalação', 'Registrar fotos antes da instalação', 50),
    (new.id, 'Instalação', 'Instalar e fixar os módulos', 60),
    (new.id, 'Elétrica', 'Executar conexões CC e CA', 70),
    (new.id, 'Elétrica', 'Realizar aterramento e testes elétricos', 80),
    (new.id, 'Finalização', 'Configurar monitoramento do inversor', 90),
    (new.id, 'Finalização', 'Registrar fotos finais', 100),
    (new.id, 'Finalização', 'Orientar o cliente e coletar assinatura', 110);
  return new;
end;
$$;

drop trigger if exists seed_service_order_checklist_after_insert on public.service_orders;
create trigger seed_service_order_checklist_after_insert
after insert on public.service_orders
for each row execute procedure public.seed_service_order_checklist();
