import React, { useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, History, Plus, Save, Search, ShieldCheck, Sun } from 'lucide-react';
import FinanceLayout from '../components/finance/FinanceLayout.jsx';
import { addAfterSalesInteraction, addWarranty, listAfterSalesInteractions, listInstalledSystems, listWarranties, updateInstalledSystem } from '../services/afterSalesService.js';

const emptyWarranty = { equipment_type: 'Módulo', brand: '', model: '', serial_number: '', warranty_years: '', warranty_start_date: '', invoice_number: '', notes: '' };
const emptyInteraction = { interaction_type: 'Acompanhamento', description: '', next_action_at: '' };

export default function PosVendaPage() {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState(null);
  const [warranties, setWarranties] = useState([]); const [interactions, setInteractions] = useState([]);
  const [warranty, setWarranty] = useState(emptyWarranty); const [interaction, setInteraction] = useState(emptyInteraction);
  const [query, setQuery] = useState(''); const [message, setMessage] = useState('');

  const load = async () => { try { setRows(await listInstalledSystems()); } catch (e) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  const open = async (item) => { setSelected(item); setForm({ ...item }); const [w, i] = await Promise.all([listWarranties(item.id), listAfterSalesInteractions(item.id)]); setWarranties(w); setInteractions(i); };
  const filtered = useMemo(() => rows.filter((r) => `${r.service_orders?.customer_name || ''} ${r.service_orders?.city || ''} ${r.consumer_unit || ''}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const stats = useMemo(() => ({ total: rows.length, homologation: rows.filter((r) => r.homologation_status !== 'Aprovada').length, monitoring: rows.filter((r) => r.monitoring_status !== 'Ativo').length, followups: rows.filter((r) => r.next_follow_up_at && new Date(r.next_follow_up_at) <= new Date()).length }), [rows]);
  const save = async () => { try { const updated = await updateInstalledSystem(form.id, form); setRows((x) => x.map((r) => r.id === updated.id ? { ...r, ...updated } : r)); setSelected({ ...selected, ...updated }); setMessage('Pós-venda atualizado.'); } catch (e) { setMessage(e.message); } };
  const createWarranty = async (e) => { e.preventDefault(); try { const created = await addWarranty(selected.id, warranty); setWarranties((x) => [...x, created]); setWarranty(emptyWarranty); setMessage('Garantia cadastrada.'); } catch (err) { setMessage(err.message); } };
  const createInteraction = async (e) => { e.preventDefault(); try { const created = await addAfterSalesInteraction(selected.id, { ...interaction, next_action_at: interaction.next_action_at ? new Date(interaction.next_action_at).toISOString() : null }); setInteractions((x) => [created, ...x]); setInteraction(emptyInteraction); setMessage('Acompanhamento registrado.'); await load(); } catch (err) { setMessage(err.message); } };

  return <FinanceLayout title="Pós-venda e sistemas instalados" subtitle="Acompanhe homologação, monitoramento, garantias e relacionamento com o cliente.">
    {message && <p className="finance-notice">{message}</p>}
    <section className="finance-kpi-grid" style={{ marginBottom: 18 }}><Kpi label="Sistemas instalados" value={stats.total}/><Kpi label="Homologações pendentes" value={stats.homologation}/><Kpi label="Monitoramentos pendentes" value={stats.monitoring}/><Kpi label="Retornos vencidos" value={stats.followups}/></section>
    <section className="finance-panel"><label className="finance-search"><Search size={18}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar cliente, cidade ou unidade consumidora"/></label><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Cliente</th><th>Sistema</th><th>Homologação</th><th>Monitoramento</th><th>Próximo contato</th><th></th></tr></thead><tbody>{filtered.map((r) => <tr key={r.id}><td><strong>{r.service_orders?.customer_name}</strong><small>{r.service_orders?.city}/{r.service_orders?.state}</small></td><td>{r.sales_proposals?.system_power_kw || 0} kWp</td><td>{r.homologation_status}</td><td>{r.monitoring_status}</td><td>{r.next_follow_up_at ? new Date(r.next_follow_up_at).toLocaleString('pt-BR') : '-'}</td><td><button onClick={() => open(r)}>Abrir</button></td></tr>)}</tbody></table></div></section>
    {selected && form && <section className="finance-panel" style={{ marginTop: 18 }}><div className="finance-panel-header"><div><h2><Sun size={21}/> {selected.service_orders?.customer_name}</h2><p>OS #{selected.service_orders?.order_number}</p></div><button className="finance-button" onClick={save}><Save size={18}/> Salvar</button></div>
      <div className="finance-form"><Field label="Concessionária" value={form.utility_company || ''} onChange={(v) => setForm({ ...form, utility_company: v })}/><Field label="Unidade consumidora" value={form.consumer_unit || ''} onChange={(v) => setForm({ ...form, consumer_unit: v })}/><Field label="Protocolo" value={form.protocol_number || ''} onChange={(v) => setForm({ ...form, protocol_number: v })}/><Select label="Homologação" value={form.homologation_status} values={['Pendente','Enviada','Em análise','Aprovada','Reprovada']} onChange={(v) => setForm({ ...form, homologation_status: v, homologation_approved_at: v === 'Aprovada' ? new Date().toISOString() : form.homologation_approved_at })}/><Field label="Plataforma de monitoramento" value={form.monitoring_platform || ''} onChange={(v) => setForm({ ...form, monitoring_platform: v })}/><Field label="Login do monitoramento" value={form.monitoring_login || ''} onChange={(v) => setForm({ ...form, monitoring_login: v })}/><Select label="Situação do monitoramento" value={form.monitoring_status} values={['Pendente','Configurando','Ativo','Sem comunicação']} onChange={(v) => setForm({ ...form, monitoring_status: v })}/><Field type="number" label="Última geração registrada (kWh)" value={form.last_generation_kwh || ''} onChange={(v) => setForm({ ...form, last_generation_kwh: Number(v) })}/><label className="finance-field finance-field-wide"><span>Observações</span><textarea value={form.notes || ''} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label></div>
      <h3><ShieldCheck size={18}/> Garantias</h3><form className="finance-form" onSubmit={createWarranty}><Select label="Equipamento" value={warranty.equipment_type} values={['Módulo','Inversor','Microinversor','Estrutura','Instalação','Outro']} onChange={(v) => setWarranty({ ...warranty, equipment_type: v })}/><Field label="Marca" value={warranty.brand} onChange={(v) => setWarranty({ ...warranty, brand: v })}/><Field label="Modelo" value={warranty.model} onChange={(v) => setWarranty({ ...warranty, model: v })}/><Field label="Número de série" value={warranty.serial_number} onChange={(v) => setWarranty({ ...warranty, serial_number: v })}/><Field type="number" label="Garantia (anos)" value={warranty.warranty_years} onChange={(v) => setWarranty({ ...warranty, warranty_years: v })}/><Field type="date" label="Início" value={warranty.warranty_start_date} onChange={(v) => setWarranty({ ...warranty, warranty_start_date: v })}/><button className="finance-button"><Plus size={17}/> Cadastrar garantia</button></form>{warranties.map((w) => <div key={w.id} className="finance-card"><CheckCircle2 size={17}/> <strong>{w.equipment_type}</strong> — {w.brand} {w.model} · até {w.warranty_end_date ? new Date(`${w.warranty_end_date}T12:00:00`).toLocaleDateString('pt-BR') : 'não informada'}</div>)}
      <h3 style={{ marginTop: 20 }}><History size={18}/> Acompanhamentos</h3><form className="finance-form" onSubmit={createInteraction}><Select label="Tipo" value={interaction.interaction_type} values={['Acompanhamento','Homologação','Monitoramento','Garantia','Manutenção','Contato com cliente']} onChange={(v) => setInteraction({ ...interaction, interaction_type: v })}/><Field label="Descrição" value={interaction.description} onChange={(v) => setInteraction({ ...interaction, description: v })}/><Field type="datetime-local" label="Próxima ação" value={interaction.next_action_at} onChange={(v) => setInteraction({ ...interaction, next_action_at: v })}/><button className="finance-button"><CalendarClock size={17}/> Registrar</button></form>{interactions.map((i) => <div key={i.id} className="finance-card"><strong>{i.interaction_type}</strong><p>{i.description}</p><small>{new Date(i.interaction_at).toLocaleString('pt-BR')}</small></div>)}
    </section>}
  </FinanceLayout>;
}
function Field({ label, value, onChange, type='text' }) { return <label className="finance-field"><span>{label}</span><input type={type} step={type === 'number' ? '0.01' : undefined} value={value} onChange={(e) => onChange(e.target.value)}/></label>; }
function Select({ label, value, values, onChange }) { return <label className="finance-field"><span>{label}</span><select value={value || ''} onChange={(e) => onChange(e.target.value)}>{values.map((v) => <option key={v}>{v}</option>)}</select></label>; }
function Kpi({ label, value }) { return <div className="finance-kpi"><span>{label}</span><strong>{value}</strong></div>; }